"""Domain event vocabulary used by the timeline, SSE stream and notifications."""

from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    INCIDENT_DETECTED = "incident.detected"
    INCIDENT_CREATED = "incident.created"
    INCIDENT_SIGNAL_ATTACHED = "incident.signal_attached"
    INCIDENT_STATUS_CHANGED = "incident.status_changed"
    INCIDENT_RESOLVED = "incident.resolved"
    INCIDENT_ESCALATED = "incident.escalated"
    INCIDENT_CLOSED = "incident.closed"
    INCIDENT_FAILED = "incident.failed"
    FLOW_SELECTED = "flow.selected"
    PHASE_ENTERED = "flow.phase_entered"
    PHASE_EXITED = "flow.phase_exited"
    AGENT_RUN_STARTED = "agent.run_started"
    AGENT_STEP = "agent.step"
    AGENT_RUN_FINISHED = "agent.run_finished"
    TOOL_REQUESTED = "tool.requested"
    TOOL_AUTHORIZED = "tool.authorized"
    TOOL_DENIED = "tool.denied"
    TOOL_EXECUTED = "tool.executed"
    TOOL_FAILED = "tool.failed"
    EVIDENCE_COLLECTED = "evidence.collected"
    HYPOTHESIS_CREATED = "hypothesis.created"
    HYPOTHESIS_UPDATED = "hypothesis.updated"
    HYPOTHESIS_VALIDATED = "hypothesis.validated"
    HYPOTHESIS_REFUTED = "hypothesis.refuted"
    REMEDIATION_PROPOSED = "remediation.proposed"
    POLICY_DECIDED = "policy.decided"
    APPROVAL_REQUESTED = "approval.requested"
    APPROVAL_DECIDED = "approval.decided"
    APPROVAL_EXPIRED = "approval.expired"
    REMEDIATION_STARTED = "remediation.started"
    REMEDIATION_COMPLETED = "remediation.completed"
    REMEDIATION_FAILED = "remediation.failed"
    REMEDIATION_SKIPPED_DUPLICATE = "remediation.skipped_duplicate"
    VERIFICATION_STARTED = "verification.started"
    VERIFICATION_PASSED = "verification.passed"
    VERIFICATION_FAILED = "verification.failed"
    ROLLBACK_STARTED = "rollback.started"
    ROLLBACK_COMPLETED = "rollback.completed"
    ROLLBACK_FAILED = "rollback.failed"
    MEMORY_STORED = "memory.stored"
    BUDGET_EXHAUSTED = "budget.exhausted"
    LLM_FALLBACK = "llm.fallback"
    NOTIFICATION = "notification"
