"""Repository ports.

Every method is async. Entities carry ``tenant_id`` and ``environment`` so that tenant scoping can
be added without a migration, but the current adapters do NOT filter by tenant: Aegis runs
single-tenant today and cross-tenant isolation is not yet enforced here.
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from aegis.domain.action import ActionExecution, ActionPlan
from aegis.domain.agent import AgentRun, AgentStep
from aegis.domain.approval import ApprovalRequest
from aegis.domain.audit import AuditEvent
from aegis.domain.enums import ApprovalStatus, IncidentStatus, Severity
from aegis.domain.evidence import Evidence, EvidenceRelation
from aegis.domain.hypothesis import Hypothesis
from aegis.domain.incident import Incident, IncidentEvent
from aegis.domain.memory import IncidentMemory, MemoryMatch
from aegis.domain.notification import Notification
from aegis.domain.tool import ToolExecutionRecord


class IncidentRepository(Protocol):
    async def add(self, incident: Incident) -> Incident: ...
    async def get(self, incident_id: uuid.UUID) -> Incident: ...
    async def find(self, incident_id: uuid.UUID) -> Incident | None: ...
    async def save(self, incident: Incident) -> Incident: ...
    async def list_incidents(
        self,
        *,
        status: Sequence[IncidentStatus] | None = None,
        severity: Sequence[Severity] | None = None,
        active_only: bool = False,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[Incident], int]: ...
    async def find_open_by_correlation(
        self, services: Sequence[str], since: datetime
    ) -> Incident | None: ...
    async def append_event(self, event: IncidentEvent) -> IncidentEvent: ...
    async def events(
        self, incident_id: uuid.UUID, after_seq: int = 0, limit: int = 500
    ) -> list[IncidentEvent]: ...
    async def count_by_status(self) -> dict[str, int]: ...


class EvidenceRepository(Protocol):
    async def add(self, evidence: Evidence) -> Evidence: ...
    async def add_many(self, items: Sequence[Evidence]) -> list[Evidence]: ...
    async def get(self, evidence_id: uuid.UUID) -> Evidence: ...
    async def list_for_incident(self, incident_id: uuid.UUID) -> list[Evidence]: ...
    async def add_relation(self, relation: EvidenceRelation) -> EvidenceRelation: ...
    async def relations_for_incident(self, incident_id: uuid.UUID) -> list[EvidenceRelation]: ...
    async def exists(self, incident_id: uuid.UUID, ids: Sequence[uuid.UUID]) -> set[uuid.UUID]: ...


class HypothesisRepository(Protocol):
    async def add(self, hypothesis: Hypothesis) -> Hypothesis: ...
    async def save(self, hypothesis: Hypothesis) -> Hypothesis: ...
    async def get(self, hypothesis_id: uuid.UUID) -> Hypothesis: ...
    async def list_for_incident(self, incident_id: uuid.UUID) -> list[Hypothesis]: ...


class ActionPlanRepository(Protocol):
    async def add(self, plan: ActionPlan) -> ActionPlan: ...
    async def save(self, plan: ActionPlan) -> ActionPlan: ...
    async def get(self, plan_id: uuid.UUID) -> ActionPlan: ...
    async def list_for_incident(self, incident_id: uuid.UUID) -> list[ActionPlan]: ...
    async def add_execution(self, execution: ActionExecution) -> ActionExecution: ...
    async def save_execution(self, execution: ActionExecution) -> ActionExecution: ...
    async def find_execution_by_key(self, idempotency_key: str) -> ActionExecution | None: ...
    async def executions_for_plan(self, plan_id: uuid.UUID) -> list[ActionExecution]: ...


class ApprovalRepository(Protocol):
    async def add(self, approval: ApprovalRequest) -> ApprovalRequest: ...
    async def save(self, approval: ApprovalRequest) -> ApprovalRequest: ...
    async def get(self, approval_id: uuid.UUID) -> ApprovalRequest: ...
    async def list_approvals(
        self,
        *,
        status: ApprovalStatus | None = None,
        incident_id: uuid.UUID | None = None,
        limit: int = 100,
    ) -> list[ApprovalRequest]: ...


class AuditRepository(Protocol):
    async def append(self, event: AuditEvent) -> AuditEvent: ...
    async def list_events(
        self, *, incident_id: uuid.UUID | None = None, limit: int = 200, offset: int = 0
    ) -> list[AuditEvent]: ...


class AgentRunRepository(Protocol):
    async def add(self, run: AgentRun) -> AgentRun: ...
    async def save(self, run: AgentRun) -> AgentRun: ...
    async def get(self, run_id: uuid.UUID) -> AgentRun: ...
    async def list_for_incident(self, incident_id: uuid.UUID) -> list[AgentRun]: ...
    async def list_recent(self, limit: int = 50) -> list[AgentRun]: ...
    async def add_step(self, step: AgentStep) -> AgentStep: ...
    async def steps_for_run(self, run_id: uuid.UUID) -> list[AgentStep]: ...
    async def steps_for_incident(self, incident_id: uuid.UUID) -> list[AgentStep]: ...


class ToolExecutionRepository(Protocol):
    async def add(self, record: ToolExecutionRecord) -> ToolExecutionRecord: ...
    async def save(self, record: ToolExecutionRecord) -> ToolExecutionRecord: ...
    async def get(self, execution_id: uuid.UUID) -> ToolExecutionRecord: ...
    async def find_by_key(self, idempotency_key: str) -> ToolExecutionRecord | None: ...
    async def list_for_incident(self, incident_id: uuid.UUID) -> list[ToolExecutionRecord]: ...
    async def count_for_run(self, agent_run_id: uuid.UUID) -> int: ...


class MemoryRepository(Protocol):
    async def add(self, memory: IncidentMemory) -> IncidentMemory: ...
    async def get_for_incident(self, incident_id: uuid.UUID) -> IncidentMemory | None: ...
    async def list_memories(
        self, limit: int = 50, offset: int = 0
    ) -> tuple[list[IncidentMemory], int]: ...
    async def search(
        self,
        embedding: list[float],
        *,
        limit: int = 5,
        exclude_incident_id: uuid.UUID | None = None,
    ) -> list[MemoryMatch]: ...
    async def search_lexical(
        self,
        terms: Sequence[str],
        services: Sequence[str],
        *,
        limit: int = 5,
        exclude_incident_id: uuid.UUID | None = None,
    ) -> list[MemoryMatch]: ...


class NotificationRepository(Protocol):
    async def add(self, notification: Notification) -> Notification: ...
    async def list_notifications(
        self, *, unread_only: bool = False, limit: int = 50
    ) -> list[Notification]: ...
    async def mark_read(self, notification_id: uuid.UUID) -> None: ...


class UnitOfWork(Protocol):
    """Transactional boundary. Repositories obtained from a UoW share one transaction."""

    @property
    def incidents(self) -> IncidentRepository: ...
    @property
    def evidence(self) -> EvidenceRepository: ...
    @property
    def hypotheses(self) -> HypothesisRepository: ...
    @property
    def action_plans(self) -> ActionPlanRepository: ...
    @property
    def approvals(self) -> ApprovalRepository: ...
    @property
    def audit(self) -> AuditRepository: ...
    @property
    def agent_runs(self) -> AgentRunRepository: ...
    @property
    def tool_executions(self) -> ToolExecutionRepository: ...
    @property
    def memories(self) -> MemoryRepository: ...
    @property
    def notifications(self) -> NotificationRepository: ...

    async def __aenter__(self) -> UnitOfWork: ...
    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self) -> UnitOfWork: ...
